### ISSUE TITLE
You might want to update MSP to MLSA :D

### ISSUE THREAD

**Issue by nirbhayvashisht** [gat786/gat786#1]
I am a Current Batch Microsoft Student Partner 🙌🏼 and soon to be Microsoft Learn Student Ambassador.

**Comment by gat786** [comment]
ayy yes let me do that.

**Comment by gat786** [comment]
Well the changes are done. If its alright we might close this issue.

**Comment by nirbhayvashisht** [comment]
Haha! I returned the favour
